//
// This source file is part of the Stanford Biodesign Digital Health Spezi Web Study Platform open-source project
//
// SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/~__root'
import { Route as dashboardLayoutRouteImport } from './routes/~(dashboard)/~layout'
import { Route as dashboardOnboardingLayoutRouteImport } from './routes/~(dashboard)/~onboarding/~layout'
import { Route as authSignInRouteImport } from './routes/~(auth)/~sign-in'
import { Route as dashboardIndexRouteImport } from './routes/~(dashboard)/~index'
import { Route as dashboardOnboardingInviteRouteImport } from './routes/~(dashboard)/~onboarding/~invite'
import { Route as dashboardOnboardingAccessPendingRouteImport } from './routes/~(dashboard)/~onboarding/~access-pending'
import { Route as dashboardTeamStudyLayoutRouteImport } from './routes/~(dashboard)/~$team/~$study/~layout'
import { Route as dashboardOnboardingIndexRouteImport } from './routes/~(dashboard)/~onboarding/~index'
import { Route as dashboardTeamIndexRouteImport } from './routes/~(dashboard)/~$team/~index'
import { Route as dashboardTeamStudyResultsRouteImport } from './routes/~(dashboard)/~$team/~$study/~results'
import { Route as dashboardTeamStudyParticipantsRouteImport } from './routes/~(dashboard)/~$team/~$study/~participants'
import { Route as dashboardTeamStudyIndexRouteImport } from './routes/~(dashboard)/~$team/~$study/~index'
import { Route as dashboardTeamStudyConfigurationBasicInformationRouteImport } from './routes/~(dashboard)/~$team/~$study/~configuration/~basic-information'
import { Route as dashboardTeamStudyConfigurationIndexRouteImport } from './routes/~(dashboard)/~$team/~$study/~configuration/~index'

const dashboardLayoutRoute = dashboardLayoutRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardOnboardingLayoutRoute =
  dashboardOnboardingLayoutRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => dashboardLayoutRoute,
  } as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardLayoutRoute,
} as any)
const dashboardOnboardingInviteRoute =
  dashboardOnboardingInviteRouteImport.update({
    id: '/invite',
    path: '/invite',
    getParentRoute: () => dashboardOnboardingLayoutRoute,
  } as any)
const dashboardOnboardingAccessPendingRoute =
  dashboardOnboardingAccessPendingRouteImport.update({
    id: '/access-pending',
    path: '/access-pending',
    getParentRoute: () => dashboardOnboardingLayoutRoute,
  } as any)
const dashboardTeamStudyLayoutRoute =
  dashboardTeamStudyLayoutRouteImport.update({
    id: '/$team/$study',
    path: '/$team/$study',
    getParentRoute: () => dashboardLayoutRoute,
  } as any)
const dashboardOnboardingIndexRoute =
  dashboardOnboardingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => dashboardOnboardingLayoutRoute,
  } as any)
const dashboardTeamIndexRoute = dashboardTeamIndexRouteImport.update({
  id: '/$team/',
  path: '/$team/',
  getParentRoute: () => dashboardLayoutRoute,
} as any)
const dashboardTeamStudyResultsRoute =
  dashboardTeamStudyResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => dashboardTeamStudyLayoutRoute,
  } as any)
const dashboardTeamStudyParticipantsRoute =
  dashboardTeamStudyParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => dashboardTeamStudyLayoutRoute,
  } as any)
const dashboardTeamStudyIndexRoute = dashboardTeamStudyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardTeamStudyLayoutRoute,
} as any)
const dashboardTeamStudyConfigurationBasicInformationRoute =
  dashboardTeamStudyConfigurationBasicInformationRouteImport.update({
    id: '/configuration/basic-information',
    path: '/configuration/basic-information',
    getParentRoute: () => dashboardTeamStudyLayoutRoute,
  } as any)
const dashboardTeamStudyConfigurationIndexRoute =
  dashboardTeamStudyConfigurationIndexRouteImport.update({
    id: '/configuration/',
    path: '/configuration/',
    getParentRoute: () => dashboardTeamStudyLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof dashboardIndexRoute
  '/sign-in': typeof authSignInRoute
  '/onboarding': typeof dashboardOnboardingLayoutRouteWithChildren
  '/$team': typeof dashboardTeamIndexRoute
  '/onboarding/': typeof dashboardOnboardingIndexRoute
  '/$team/$study': typeof dashboardTeamStudyLayoutRouteWithChildren
  '/onboarding/access-pending': typeof dashboardOnboardingAccessPendingRoute
  '/onboarding/invite': typeof dashboardOnboardingInviteRoute
  '/$team/$study/': typeof dashboardTeamStudyIndexRoute
  '/$team/$study/participants': typeof dashboardTeamStudyParticipantsRoute
  '/$team/$study/results': typeof dashboardTeamStudyResultsRoute
  '/$team/$study/configuration': typeof dashboardTeamStudyConfigurationIndexRoute
  '/$team/$study/configuration/basic-information': typeof dashboardTeamStudyConfigurationBasicInformationRoute
}
export interface FileRoutesByTo {
  '/': typeof dashboardIndexRoute
  '/sign-in': typeof authSignInRoute
  '/$team': typeof dashboardTeamIndexRoute
  '/onboarding': typeof dashboardOnboardingIndexRoute
  '/onboarding/access-pending': typeof dashboardOnboardingAccessPendingRoute
  '/onboarding/invite': typeof dashboardOnboardingInviteRoute
  '/$team/$study': typeof dashboardTeamStudyIndexRoute
  '/$team/$study/participants': typeof dashboardTeamStudyParticipantsRoute
  '/$team/$study/results': typeof dashboardTeamStudyResultsRoute
  '/$team/$study/configuration': typeof dashboardTeamStudyConfigurationIndexRoute
  '/$team/$study/configuration/basic-information': typeof dashboardTeamStudyConfigurationBasicInformationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)': typeof dashboardLayoutRouteWithChildren
  '/(dashboard)/': typeof dashboardIndexRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(dashboard)/onboarding': typeof dashboardOnboardingLayoutRouteWithChildren
  '/(dashboard)/$team/': typeof dashboardTeamIndexRoute
  '/(dashboard)/onboarding/': typeof dashboardOnboardingIndexRoute
  '/(dashboard)/$team/$study': typeof dashboardTeamStudyLayoutRouteWithChildren
  '/(dashboard)/onboarding/access-pending': typeof dashboardOnboardingAccessPendingRoute
  '/(dashboard)/onboarding/invite': typeof dashboardOnboardingInviteRoute
  '/(dashboard)/$team/$study/': typeof dashboardTeamStudyIndexRoute
  '/(dashboard)/$team/$study/participants': typeof dashboardTeamStudyParticipantsRoute
  '/(dashboard)/$team/$study/results': typeof dashboardTeamStudyResultsRoute
  '/(dashboard)/$team/$study/configuration/': typeof dashboardTeamStudyConfigurationIndexRoute
  '/(dashboard)/$team/$study/configuration/basic-information': typeof dashboardTeamStudyConfigurationBasicInformationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/onboarding'
    | '/$team'
    | '/onboarding/'
    | '/$team/$study'
    | '/onboarding/access-pending'
    | '/onboarding/invite'
    | '/$team/$study/'
    | '/$team/$study/participants'
    | '/$team/$study/results'
    | '/$team/$study/configuration'
    | '/$team/$study/configuration/basic-information'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/$team'
    | '/onboarding'
    | '/onboarding/access-pending'
    | '/onboarding/invite'
    | '/$team/$study'
    | '/$team/$study/participants'
    | '/$team/$study/results'
    | '/$team/$study/configuration'
    | '/$team/$study/configuration/basic-information'
  id:
    | '__root__'
    | '/(dashboard)'
    | '/(dashboard)/'
    | '/(auth)/sign-in'
    | '/(dashboard)/onboarding'
    | '/(dashboard)/$team/'
    | '/(dashboard)/onboarding/'
    | '/(dashboard)/$team/$study'
    | '/(dashboard)/onboarding/access-pending'
    | '/(dashboard)/onboarding/invite'
    | '/(dashboard)/$team/$study/'
    | '/(dashboard)/$team/$study/participants'
    | '/(dashboard)/$team/$study/results'
    | '/(dashboard)/$team/$study/configuration/'
    | '/(dashboard)/$team/$study/configuration/basic-information'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardLayoutRoute: typeof dashboardLayoutRouteWithChildren
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)': {
      id: '/(dashboard)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/onboarding': {
      id: '/(dashboard)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof dashboardOnboardingLayoutRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/onboarding/invite': {
      id: '/(dashboard)/onboarding/invite'
      path: '/invite'
      fullPath: '/onboarding/invite'
      preLoaderRoute: typeof dashboardOnboardingInviteRouteImport
      parentRoute: typeof dashboardOnboardingLayoutRoute
    }
    '/(dashboard)/onboarding/access-pending': {
      id: '/(dashboard)/onboarding/access-pending'
      path: '/access-pending'
      fullPath: '/onboarding/access-pending'
      preLoaderRoute: typeof dashboardOnboardingAccessPendingRouteImport
      parentRoute: typeof dashboardOnboardingLayoutRoute
    }
    '/(dashboard)/$team/$study': {
      id: '/(dashboard)/$team/$study'
      path: '/$team/$study'
      fullPath: '/$team/$study'
      preLoaderRoute: typeof dashboardTeamStudyLayoutRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/onboarding/': {
      id: '/(dashboard)/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof dashboardOnboardingIndexRouteImport
      parentRoute: typeof dashboardOnboardingLayoutRoute
    }
    '/(dashboard)/$team/': {
      id: '/(dashboard)/$team/'
      path: '/$team'
      fullPath: '/$team'
      preLoaderRoute: typeof dashboardTeamIndexRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/$team/$study/results': {
      id: '/(dashboard)/$team/$study/results'
      path: '/results'
      fullPath: '/$team/$study/results'
      preLoaderRoute: typeof dashboardTeamStudyResultsRouteImport
      parentRoute: typeof dashboardTeamStudyLayoutRoute
    }
    '/(dashboard)/$team/$study/participants': {
      id: '/(dashboard)/$team/$study/participants'
      path: '/participants'
      fullPath: '/$team/$study/participants'
      preLoaderRoute: typeof dashboardTeamStudyParticipantsRouteImport
      parentRoute: typeof dashboardTeamStudyLayoutRoute
    }
    '/(dashboard)/$team/$study/': {
      id: '/(dashboard)/$team/$study/'
      path: '/'
      fullPath: '/$team/$study/'
      preLoaderRoute: typeof dashboardTeamStudyIndexRouteImport
      parentRoute: typeof dashboardTeamStudyLayoutRoute
    }
    '/(dashboard)/$team/$study/configuration/basic-information': {
      id: '/(dashboard)/$team/$study/configuration/basic-information'
      path: '/configuration/basic-information'
      fullPath: '/$team/$study/configuration/basic-information'
      preLoaderRoute: typeof dashboardTeamStudyConfigurationBasicInformationRouteImport
      parentRoute: typeof dashboardTeamStudyLayoutRoute
    }
    '/(dashboard)/$team/$study/configuration/': {
      id: '/(dashboard)/$team/$study/configuration/'
      path: '/configuration'
      fullPath: '/$team/$study/configuration'
      preLoaderRoute: typeof dashboardTeamStudyConfigurationIndexRouteImport
      parentRoute: typeof dashboardTeamStudyLayoutRoute
    }
  }
}

interface dashboardOnboardingLayoutRouteChildren {
  dashboardOnboardingIndexRoute: typeof dashboardOnboardingIndexRoute
  dashboardOnboardingAccessPendingRoute: typeof dashboardOnboardingAccessPendingRoute
  dashboardOnboardingInviteRoute: typeof dashboardOnboardingInviteRoute
}

const dashboardOnboardingLayoutRouteChildren: dashboardOnboardingLayoutRouteChildren =
  {
    dashboardOnboardingIndexRoute: dashboardOnboardingIndexRoute,
    dashboardOnboardingAccessPendingRoute:
      dashboardOnboardingAccessPendingRoute,
    dashboardOnboardingInviteRoute: dashboardOnboardingInviteRoute,
  }

const dashboardOnboardingLayoutRouteWithChildren =
  dashboardOnboardingLayoutRoute._addFileChildren(
    dashboardOnboardingLayoutRouteChildren,
  )

interface dashboardTeamStudyLayoutRouteChildren {
  dashboardTeamStudyIndexRoute: typeof dashboardTeamStudyIndexRoute
  dashboardTeamStudyParticipantsRoute: typeof dashboardTeamStudyParticipantsRoute
  dashboardTeamStudyResultsRoute: typeof dashboardTeamStudyResultsRoute
  dashboardTeamStudyConfigurationIndexRoute: typeof dashboardTeamStudyConfigurationIndexRoute
  dashboardTeamStudyConfigurationBasicInformationRoute: typeof dashboardTeamStudyConfigurationBasicInformationRoute
}

const dashboardTeamStudyLayoutRouteChildren: dashboardTeamStudyLayoutRouteChildren =
  {
    dashboardTeamStudyIndexRoute: dashboardTeamStudyIndexRoute,
    dashboardTeamStudyParticipantsRoute: dashboardTeamStudyParticipantsRoute,
    dashboardTeamStudyResultsRoute: dashboardTeamStudyResultsRoute,
    dashboardTeamStudyConfigurationIndexRoute:
      dashboardTeamStudyConfigurationIndexRoute,
    dashboardTeamStudyConfigurationBasicInformationRoute:
      dashboardTeamStudyConfigurationBasicInformationRoute,
  }

const dashboardTeamStudyLayoutRouteWithChildren =
  dashboardTeamStudyLayoutRoute._addFileChildren(
    dashboardTeamStudyLayoutRouteChildren,
  )

interface dashboardLayoutRouteChildren {
  dashboardIndexRoute: typeof dashboardIndexRoute
  dashboardOnboardingLayoutRoute: typeof dashboardOnboardingLayoutRouteWithChildren
  dashboardTeamIndexRoute: typeof dashboardTeamIndexRoute
  dashboardTeamStudyLayoutRoute: typeof dashboardTeamStudyLayoutRouteWithChildren
}

const dashboardLayoutRouteChildren: dashboardLayoutRouteChildren = {
  dashboardIndexRoute: dashboardIndexRoute,
  dashboardOnboardingLayoutRoute: dashboardOnboardingLayoutRouteWithChildren,
  dashboardTeamIndexRoute: dashboardTeamIndexRoute,
  dashboardTeamStudyLayoutRoute: dashboardTeamStudyLayoutRouteWithChildren,
}

const dashboardLayoutRouteWithChildren = dashboardLayoutRoute._addFileChildren(
  dashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  dashboardLayoutRoute: dashboardLayoutRouteWithChildren,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
